version: '3.0'

services:
  importer:
    image: aegisbigdata/harvester-importer
    logging:
      options:
        max-size: "1g"
    ports:
      - "8080:8080"
    volumes:
      - log-volume:/log
      - tmp-volume:/tmp
  transformer:
    image: aegisbigdata/harvester-transformer
    logging:
      options:
        max-size: "1g"
  aggregator:
    image: aegisbigdata/harvester-aggregator
    logging:
      options:
        max-size: "1g"
    volumes:
      - log-volume:/log
      - tmp-volume:/tmp
  exporter:
    image: aegisbigdata/harvester-exporter
    logging:
      options:
        max-size: "1g"
    volumes:
      - log-volume:/log
      - tmp-volume:/tmp
  harvester-ui:
    image: aegisbigdata/harvester-ui:latest
    logging:
      options:
        max-size: "1g"
    container_name: harvester-ui
    ports:
      - 8081:8080

volumes:
  log-volume:
  tmp-volume:
  aggregator-volume:

