openapi: 3.0.0

info:
  version: 0.0.1-alpha
  title: Transformer
  x-logo:
    url: ""

servers:
  - url: 'http://localhost:8081'
    description: Local development server

paths:
  /transform:
    post:
      description: Transform various types of data into CSV
      summary: The resulting CSV is sent line by line to the next service, with the CSV headers included in every request
      operationId: transform
      requestBody:
        description: Transformation details
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/TransformationRequest'
            examples:
              owmTransformationExample:
                $ref: '#/components/examples/owmTransformationExample'
              csvTransformationExample:
                $ref: '#/components/examples/csvTransformationExample'
              eventTransformationExample:
                $ref: '#/components/examples/eventTransformationExample'

      responses:
        '202':
          description: Request accepted
        '400':
          description: Invalid request. Either malformed JSON was provided or required fields are missing/misspelled

components:
  schemas:
    TransformationRequest:
      description: All data required for performing the desired transformation
      type: object
      required:
        - pipeId
        - hopsProjectId
        - hopsDataset
        - dataType
        - payload
      properties:
        pipeId:
            description: A unique ID to identify the pipe the request belongs to
            type: string
        hopsProjectId:
            description: The project ID in hopsworks in which the hopsDataset resides
            type: string
        hopsDataset:
            description: The dataset in hopsworks to upload the resulting CSV file to
            type: string
        dataType:
            description: Enum indication whether the payload consists of OWM or CSV data
            type: string
            enum: [OWM, CSV, EVENT]
        payload:
            description: Either JSON containing OWM weather data or JSON containing 'csv' data and a 'mapping'
            type: string
  examples:
    owmTransformationExample:
      summary: A request to transform OWM data
      value: {
               "pipeId" : "samplePipe",
               "hopsProjectId" : 123,
               "hopsDataset" : "myDataset",
               "dataType" : "OWM",
               "payload" : "{\"coord\":{\"lon\":14.44, ... }"
             }
    csvTransformationExample:
      summary: A request to transform CSV data
      value: {
               "pipeId" : "samplePipe",
               "hopsProjectId" : 123,
               "hopsDataset" : "myDataset",
               "dataType" : "CSV",
               "payload" : "{\"csv\" : \"data_1,data_2, ... \", \"mapping\" : \" see README for explanation of available mappings \"}"
             }
    eventTransformationExample:
      summary: A request to transform CSV data
      value: {
               "pipeId" : "samplePipe",
               "hopsProjectId" : 123,
               "hopsDataset" : "myDataset",
               "dataType" : "EVENT",
               "payload" : "TODO"
             }